version: '2'
services:
  grafana:
    container_name: "grafana"
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    ports:
      - "3000:3000"
    networks:
      - local
    volumes:
      - ./.data/grafana:/var/lib/grafana

networks:
  local:
    driver: bridge
