version: '2'
networks:
  public:
    driver: bridge
  private:
    driver: bridge

services:

  proxy:
    container_name: "proxy"
    extends:
      file: ./proxy/docker-compose.yml
      service: http # Specify `https` instead for a secure connection
    depends_on:
     - consul-host
     - registrator
     - registry
     - portainer
     - tests-python
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - public

  registrator:
    image: gliderlabs/registrator:master
    hostname: registrator
    container_name: "registrator"
    command: "-internal consul://consul-host:8500"
    depends_on:
     - consul-host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - public

  consul-host:
    extends:
      file: ./devops/consol/docker-compose.yml
      service: consul-host
    networks:
      - public

  registry:
    extends:
      file: ./devops/registry/docker-compose.yml
      service: registry
    networks:
      - public

  portainer:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-app
    depends_on:
      - portainer-tpl
    networks:
      - public

  portainer-tpl:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-tpl
    networks:
      - public

  tests-python:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python
    depends_on:
     - tests-python-redis
    networks:
      - public

  tests-python-redis:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python-redis
    networks:
      - public
