version: '2'
networks:
  public:
    driver: bridge
services:
  # -----------------------------------------------------------------------------------------
  # Public Proxy
  # -----------------------------------------------------------------------------------------
  # You can specify one of the following proxy types:
  # proxy -> extends -> service:
  #  = `http`     - basic http proxy (insecure, self-signed)
  #  = `https`    - secured proxy built on top of `https://letsencrypt.org/`
  #  = `gateway`  - advanced proxy gateway with config and service auto discovery included
  # -----------------------------------------------------------------------------------------
  proxy:
    container_name: "proxy"
    extends:
      file: ./components/proxy/docker-compose.yml
      service: gateway # Specify `http`, `https` or `gateway`
    depends_on:
     - consul
     - registrator
     - registry
     - portainer
     - test-py
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - public

  # -----------------------------------------------------------------------------------------
  # Devops internals
  # -----------------------------------------------------------------------------------------
  consul:
    container_name: "consul"
    extends:
      file: ./components/consul/docker-compose.yml
      service: consul
    networks:
      - public

  registrator:
    container_name: "registrator"
    hostname: "registrator"
    image: "gliderlabs/registrator:master"
    command: "-internal consul://consul:8500"
    depends_on:
     - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    networks:
      - public


  # -----------------------------------------------------------------------------------------
  # Build and promotion pipeline
  # -----------------------------------------------------------------------------------------
  registry:
    extends:
      file: ./components/registry/docker-compose.yml
      service: registry
    networks:
      - public


  # -----------------------------------------------------------------------------------------
  # Docker administration
  # -----------------------------------------------------------------------------------------
  portainer:
    extends:
      file: ./components/portainer/docker-compose.yml
      service: portainer
    depends_on:
      - portainer-api
    networks:
      - public

  portainer-api:
    extends:
      file: ./components/portainer/docker-compose.yml
      service: portainer-api
    networks:
      - public


  # -----------------------------------------------------------------------------------------
  # Testing containers
  # -----------------------------------------------------------------------------------------
  test-py:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python
    depends_on:
     - test-py-redis
    networks:
      - public

  test-py-redis:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python-redis
    networks:
      - public
