version: '2'
services:
  # -----------------------------------------------------------------------------------------
  # Public Proxy
  # -----------------------------------------------------------------------------------------
  # You can specify one of the following proxy types:
  # proxy -> extends -> service:
  #  = `http`     - basic http proxy (insecure, self-signed)
  #  = `https`    - secured proxy built on top of `https://letsencrypt.org/`
  #  = `gateway`  - advanced proxy gateway with config and service auto discovery included
  # -----------------------------------------------------------------------------------------
  proxy:
    container_name: "proxy"
    extends:
      file: ./components/proxy/docker-compose.yml
      service: gateway # Specify `http`, `https` or `gateway`
    env_file:
      - ./.env
    volumes_from:
      - www
    depends_on:
     - consul
     - registrator
     - portainer
     - registry
     - test-py
    ports:
      - "8080:80"
      - "8443:443"

  www:
    container_name: "www"
    image: "example.com:5000/www:latest"
    volumes:
     - ./www:/www:rw

  # -----------------------------------------------------------------------------------------
  # Devops internals
  # -----------------------------------------------------------------------------------------
  consul:
    container_name: "consul"
    extends:
      file: ./components/consul/docker-compose.yml
      service: consul

  registrator:
    container_name: "registrator"
    extends:
      file: ./components/registrator/docker-compose.yml
      service: registrator
    depends_on:
     - consul

  # -----------------------------------------------------------------------------------------
  # Build and promotion pipeline
  # -----------------------------------------------------------------------------------------
  registry:
    container_name: "registry"
    extends:
      file: ./components/registry/docker-compose.yml
      service: registry


  # -----------------------------------------------------------------------------------------
  # Docker administration
  # -----------------------------------------------------------------------------------------
  portainer:
    extends:
      file: ./components/portainer/docker-compose.yml
      service: portainer
    depends_on:
      - portainer-api

  portainer-api:
    extends:
      file: ./components/portainer/docker-compose.yml
      service: portainer-api


  # -----------------------------------------------------------------------------------------
  # Testing containers
  # -----------------------------------------------------------------------------------------
  test-py:
    extends:
      file: ./projects/tests-py/docker-compose.yml
      service: tests-python
    depends_on:
     - test-py-redis

  test-py-redis:
    extends:
      file: ./projects/tests-py/docker-compose.yml
      service: tests-python-redis
