version: '2'
networks:
  local:
    driver: bridge
services:

  proxy:
    container_name: "proxy"
    extends:
      file: ./proxy/docker-compose.yml
      service: http # Specify `https` instead for a secure connection
    depends_on:
     - portainer
     - tests-python
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - local

  registry:
    extends:
      file: ./devops/registry/docker-compose.yml
      service: registry
    ports:
      - "5000:5000"
    networks:
      - local

  portainer:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-app
    depends_on:
      - portainer-tpl
    ports:
      - "9000:9000"
    networks:
      - local
  portainer-tpl:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-tpl
    networks:
      - local

  tests-python:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python
    depends_on:
     - tests-python-redis
    networks:
      - local

  tests-python-redis:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python-redis
    networks:
      - local
