version: '2'
services:

  gateway:
    container_name: "gateway"
    extends:
        file: ./src/nginx/docker-compose.yml
        service: gateway
    depends_on:
     - test

  test:
    container_name: "python-redis-test"
    extends:
        file: ./src/python-redis-test/docker-compose.yml
        service: python-redis-test
    depends_on:
     - redis

  redis:
    container_name: "redis-storage"
    image: "redis:alpine"
