version: '2'
services:
  http:
    container_name: "http"
    extends:
      file: ./src/nginx/docker-compose.yml
      service: gateway
    depends_on:
     - test
     - portainer
    networks:
      - local

  portainer:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-app
    depends_on:
      - portainer-tpl
    networks:
      - local
  portainer-tpl:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-tpl
    networks:
      - local

  test:
    container_name: "python-redis-test"
    extends:
      file: ./src/python-redis-test/docker-compose.yml
      service: python-redis-test
    depends_on:
     - redis
    networks:
      - local

  redis:
    container_name: "storage-redis"
    image: redis:alpine
    networks:
      - local

networks:
  local:
    driver: bridge
