version: '2'
networks:
  local:
    driver: bridge

services:
  http:
    extends:
      file: ./proxy/gateway.yml
      service: http
    depends_on:
     - portainer
     - tests-python
    networks:
      - local

  portainer:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-app
    depends_on:
      - portainer-tpl
    networks:
      - local
  portainer-tpl:
    extends:
      file: ./devops/portainer/docker-compose.yml
      service: portainer-tpl
    networks:
      - local

  tests-python:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python
    depends_on:
     - tests-python-redis
    networks:
      - local
  tests-python-redis:
    extends:
      file: ./src/tests/python/docker-compose.yml
      service: tests-python-redis
    networks:
      - local
