version: '2'
services:

  portainer:
    image: "example.com:5000/portainer:latest"
    command: --templates http://portainer-tpl/app.templates.json -d /data
    environment:
     - SERVICE_NAME=portainer
     - SERVICE_TAGS=app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data:/data

  portainer-api:
    image: "example.com:5000/portainer/templates:latest"
    environment:
     - SERVICE_NAME=portainer-api
     - SERVICE_TAGS=api
    volumes:
     - ./templates:/usr/share/nginx/html/
