version: '2'
services:

  portainer:
    image: "example.com:5000/portainer:latest"
    command: "--templates http://portainer-api:8100/ -d /data"
    environment:
     - SERVICE_NAME=portainer
     - SERVICE_TAGS=app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.data:/data

  portainer-api:
    image: "example.com:5000/portainer/api:latest"
    environment:
     - SERVICE_NAME=portainer-api
     - SERVICE_TAGS=api
    ports:
      - "8100"
    volumes:
     - ./api/service:/usr/src/app/service/
