version: '2'
services:
  dray:
    image: centurylink/dray
    links:
     - redis
    environment:
     - REDIS_PORT=6379
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - "3000:3000"

  redis:
    image: redis