version: '2'
services:
  grafana:
    container_name: "grafana"
    image: "grafana/grafana"
    environment:
     - GF_SECURITY_ADMIN_PASSWORD=secret
     - SERVICE_NAME=grafana
     - SERVICE_TAGS=app
    ports:
      - "3000:3000"
    volumes:
      - ./.data/grafana:/var/lib/grafana