version: '2'
services:

  http:
    container_name: "http"
    image: "proxy/http:latest"
    build: ./http
    environment:
      STAGE: insecure

  https:
    container_name: "https"
    image: "proxy/https:latest"
    build: ./https
    environment:
      STAGE: local # or "production"
      DOMAINS: "example.com"
