version: '2'
services:

  http:
    container_name: "http"
    image: "proxy/http:latest"
    build: ./http
    environment:
      STAGE: insecure
    volumes:
     - ./config:/etc/nginx/conf.d/:ro
     - ./www:/usr/share/nginx/html:ro

  https:
    container_name: "https"
    image: "proxy/https:latest"
    build: ./https
    environment:
      STAGE: local # or "production"
      DOMAINS: "example.com"
      #DOMAINS: 'my.example.domain -> https://letsencrypt.org, another.example.domain -> https://another.upstream'
    volumes:
     #- ./.data/certs:/var/lib/https-portal
     - ./www:/var/www/vhosts/example.com/:ro
