version: '2'
services:

  http:
    container_name: "http"
    image: "proxy/http:latest"
    build: ./http
    environment:
      STAGE: insecure
      DOMAINS: "example.com"
    volumes:
     - ./http/certs:/etc/nginx/certs/:ro
     - ./http/config:/etc/nginx/conf.d/:ro
     - ../www:/usr/share/nginx/html:ro

  https:
    container_name: "https"
    image: "proxy/https:latest"
    build: ./https
    environment:
      STAGE: local # or "production"
      DOMAINS: "example.com"
      #DOMAINS: "example.com -> https://https/, test.example.com -> https://python/, manage.example.com -> https://protainer"
    volumes:
     - ./https/.certs:/var/lib/https-portal:rw
     - ./https/config/routes.conf.erb:/var/lib/nginx-conf/my.example.com.conf.erb:ro
     - ./https/config/routes.ssl.conf.erb:/var/lib/nginx-conf/my.example.com.ssl.conf.erb:ro
     - ../www:/var/www/vhosts/example.com/:ro
