version: '2'
services:

  http:
    image: "example.com:5000/proxy/http:latest"

  https:
    image: "example.com:5000/proxy/https:latest"
    environment:
      STAGE: local # or "production"
      DOMAINS: "example.com"
    volumes:
     - ./certs/data:/var/lib/https-portal:rw

  gateway:
    image: "example.com:5000/proxy/gateway:latest"
    environment:
      CONSUL_URL: "consul:8500"
      #CONFIG_SRC: "/etc/nginx/conf.d/nginx.proxies.ctmpl"
      #CONFIG_DST: "/etc/nginx/conf.d/nginx.tmp.conf"
