version: "2"
services:

  consul:
    image: "progrium/consul:latest"
    container_name: "consul"
    hostname: "consul"
    command: "-server -bootstrap -ui-dir /ui"
    environment:
     - SERVICE_NAME=consul
     - SERVICE_TAGS=app:8500/consul/ui/
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"

  consul-slave:
    image: "progrium/consul:latest"
    hostname: "consul-slave"
    environment:
     - SERVICE_NAME=consul-slave
     - SERVICE_TAGS=app:8500
    expose:
      - "8400"
      - "8500"
      - "8600"
    command: "-server -join consul"
    depends_on:
      - consul